name: GitHub Actions Demo
run-name: pipeline test 🚀
on: [push]
jobs:

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://dev.example.com
    steps:
      - run: echo hello world dev

  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://dev.example.com

    needs: [deploy-dev]
    steps:
      - run: echo hmg


  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://dev.example.com

    needs: [deploy-dev]
    steps:
      - run: echo production
